# Introduction
Modifying the Notebook that Idir did so I obly take the portrait painting

# Libraries

In [12]:
import pandas as pd
import os
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time

In [13]:
data_file = "../../data/art_catalog.xlsx"
df = pd.read_excel(data_file)
df.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
0,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Venus and Adonis,1574-88,"Oil on canvas, 68 x 95 cm","Fogg Art Museum, Harvard University, Cambridge",https://www.wga.hu/html/a/aachen/adonis.html,painting,mythological,German,1601-1650
1,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Allegory,1598,"Oil on copper, 56 x 47 cm","Alte Pinakothek, Munich",https://www.wga.hu/html/a/aachen/allegory.html,painting,mythological,German,1601-1650
2,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Allegory of Peace, Art and Abundance",1602,"Oil on canvas, 197 x 142 cm","The Hermitage, St. Petersburg",https://www.wga.hu/html/a/aachen/allegorz.html,painting,mythological,German,1601-1650
3,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Jupiter, Antiope and Cupid",1595-98,"Oil on copper, 31 x 21 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/antiope.html,painting,mythological,German,1601-1650
4,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Pallas Athena, Venus and Juno",1593,"Oil on canvas, 54 x 67 cm","Museum of Fine Arts, Boston",https://www.wga.hu/html/a/aachen/athena.html,painting,mythological,German,1601-1650

Selectionne uniquement les "FORM == painting""

In [4]:
df_paint = df[(df["FORM"] == "painting") & (df["TYPE"] == "portrait")]
df_paint.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
12,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Gaspar Rem,1574-75,"Oil on canvas, 49 x 42 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/portrai1.html,painting,portrait,German,1601-1650
13,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Portrait of Painter Josef Heintz,1585,"Oil on canvas, 57 x 44 cm","Národní Galerie, Prague",https://www.wga.hu/html/a/aachen/portrai2.html,painting,portrait,German,1601-1650
14,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Anna of Tyrol,1604,"Oil on canvas, 58 x 48 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/portrai3.html,painting,portrait,German,1601-1650
16,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Portrait of Emperor Rudolf II,1606-08,"Oil on canvas, 60 x 48 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/rudolf2.html,painting,portrait,German,1601-1650
17,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Two Laughing Men (Self-Portrait),before 1574,"Oil on panel, 48 x 39 cm","Archdiocesan Museum, Kromeriz",https://www.wga.hu/html/a/aachen/selfpor1.html,painting,portrait,German,1601-1650

In [5]:
df_paint.shape

(4810, 11)

In [6]:
urls = list(df_paint["URL"])

urls[:5]

['https://www.wga.hu/html/a/aachen/portrai1.html',
 'https://www.wga.hu/html/a/aachen/portrai2.html',
 'https://www.wga.hu/html/a/aachen/portrai3.html',
 'https://www.wga.hu/html/a/aachen/rudolf2.html',
 'https://www.wga.hu/html/a/aachen/selfpor1.html']

# IDEA ABORTED
TROP LENT. Je vais juste copier les images télécharger par Idier et prendre seulement les portraits.

In [14]:
import pandas as pd

# Si ton fichier est en CSV :
data_file = "../../data/art_catalog.xlsx"
df = pd.read_excel(data_file)

print(df.columns)  # pour vérifier que "TYPE" et "URL" existent bien

Index(['AUTHOR', 'BORN-DIED', 'TITLE', 'DATE', 'TECHNIQUE', 'LOCATION', 'URL',
       'FORM', 'TYPE', 'SCHOOL', 'TIMEFRAME'],
      dtype='object')

In [15]:
# On garde les lignes où :
#   - FORM contient "painting"
#   - TYPE contient "portrait"
df_portraits = df[
    df["FORM"].str.lower().str.contains("painting", na=False)
    & df["TYPE"].str.lower().str.contains("landscap", na=False)
].copy()

print(f"Nombre total de lignes : {len(df)}")
print(f"Nombre de portraits : {len(df_portraits)}")

Nombre total de lignes : 52867
Nombre de portraits : 4103

In [16]:
def page_url_to_filename(page_url: str) -> str:
    img_url = page_url.replace("/html/", "/detail/").replace(".html", ".jpg")
    return img_url.split("/")[-1]

df_portraits["fname"] = df_portraits["URL"].apply(page_url_to_filename)

In [18]:
import os, shutil

src_dir = "../../data/raw/all"
dst_dir = "../../data/processed/landscapes"
os.makedirs(dst_dir, exist_ok=True)

copied = 0
missing = []

for fname in df_portraits["fname"].unique():
    src = os.path.join(src_dir, fname)
    dst = os.path.join(dst_dir, fname)
    if os.path.exists(src):
        shutil.copy2(src, dst)
        copied += 1
    else:
        missing.append(fname)

print(f"✅ {copied} portraits copiés dans {dst_dir}")
print(f"⚠️ {len(missing)} fichiers manquants (peut-être non téléchargés)")

✅ 3051 portraits copiés dans ../../data/processed/landscapes
⚠️ 0 fichiers manquants (peut-être non téléchargés)

In [4]:
df.columns

Index(['AUTHOR', 'BORN-DIED', 'TITLE', 'DATE', 'TECHNIQUE', 'LOCATION', 'URL',
       'FORM', 'TYPE', 'SCHOOL', 'TIMEFRAME'],
      dtype='object')

In [8]:
df_paint = df[df["FORM"] == "painting"]

In [9]:
df_paint.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
0,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Venus and Adonis,1574-88,"Oil on canvas, 68 x 95 cm","Fogg Art Museum, Harvard University, Cambridge",https://www.wga.hu/html/a/aachen/adonis.html,painting,mythological,German,1601-1650
1,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)",Allegory,1598,"Oil on copper, 56 x 47 cm","Alte Pinakothek, Munich",https://www.wga.hu/html/a/aachen/allegory.html,painting,mythological,German,1601-1650
2,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Allegory of Peace, Art and Abundance",1602,"Oil on canvas, 197 x 142 cm","The Hermitage, St. Petersburg",https://www.wga.hu/html/a/aachen/allegorz.html,painting,mythological,German,1601-1650
3,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Jupiter, Antiope and Cupid",1595-98,"Oil on copper, 31 x 21 cm","Kunsthistorisches Museum, Vienna",https://www.wga.hu/html/a/aachen/antiope.html,painting,mythological,German,1601-1650
4,"AACHEN, Hans von","(b. 1552, Köln, d. 1615, Praha)","Pallas Athena, Venus and Juno",1593,"Oil on canvas, 54 x 67 cm","Museum of Fine Arts, Boston",https://www.wga.hu/html/a/aachen/athena.html,painting,mythological,German,1601-1650

In [10]:
df_paint['SCHOOL'].value_counts()

SCHOOL
Italian          13743
French            4410
Dutch             4375
Flemish           3697
German            1923
Spanish           1250
English            681
Netherlandish      514
Austrian           391
Hungarian          345
American           178
Swiss              134
Danish             125
Russian            111
Belgian            105
Scottish            74
Norwegian           55
Catalan             51
Greek               47
Bohemian            47
Other               41
Swedish             37
Irish               33
Finnish             28
Portuguese          25
Polish              18
Name: count, dtype: int64

In [11]:
df_paint['TYPE'].value_counts()

TYPE
religious       13517
portrait         4810
landscape        4103
mythological     3202
genre            2772
still-life       1405
other             970
historical        943
interior          636
study              80
Name: count, dtype: int64

# Creating a file for the French and for the Dutch style

In [1]:
import pandas as pd

# Si ton fichier est en CSV :
data_file = "../../data/art_catalog.xlsx"
df = pd.read_excel(data_file)

print(df.columns)  # pour vérifier que "TYPE" et "URL" existent bien

Index(['AUTHOR', 'BORN-DIED', 'TITLE', 'DATE', 'TECHNIQUE', 'LOCATION', 'URL',
       'FORM', 'TYPE', 'SCHOOL', 'TIMEFRAME'],
      dtype='object')

In [2]:
df_french = df[(df["SCHOOL"] == "French") & (df["FORM"] == "painting")]
df_french.head(5)

,AUTHOR,BORN-DIED,TITLE,DATE,TECHNIQUE,LOCATION,URL,FORM,TYPE,SCHOOL,TIMEFRAME
501,"ALLEGRAIN, Etienne","(b. 1644, Paris, d. 1736, Paris)",Landscape with the Finding of Moses,-,"Oil on canvas, 88 x 115 cm","The Hermitage, St. Petersburg",https://www.wga.hu/html/a/allegrai/etienne/lan...,painting,landscape,French,1651-1700
502,"ALLEGRAIN, Etienne","(b. 1644, Paris, d. 1736, Paris)",River Landscape,-,Oil on canvas : 118 x 92 cm,"Musée National du Château, Versailles",https://www.wga.hu/html/a/allegrai/etienne/riv...,painting,landscape,French,1651-1700
503,"ALLEGRAIN, Etienne","(b. 1644, Paris, d. 1736, Paris)",River Landscape,-,Oil on canvas : 86 x 136 cm,"Musée du Louvre, Paris",https://www.wga.hu/html/a/allegrai/etienne/riv...,painting,landscape,French,1651-1700
1314,"ANGRAND, Charles","(b. 1854, Criquetot-sur-Ouville, d. 1926, Rouen)",Couple in the Street,1887,"Oil on canvas on card, 39 x 33 cm","Musée d'Orsay, Paris",https://www.wga.hu/html/a/angrand/couple.html,painting,genre,French,1851-1900
1315,"ANGRAND, Charles","(b. 1854, Criquetot-sur-Ouville, d. 1926, Rouen)",The Western Railway Leaving Paris,1886,"Oil on canvas, 75 x 92 cm",Private collection,https://www.wga.hu/html/a/angrand/railway.html,painting,landscape,French,1851-1900

In [3]:
# On garde les lignes où :
#   - FORM contient "painting"
#   - TYPE contient "portrait"
df_french = df[(df["SCHOOL"] == "French") & (df["FORM"] == "painting")]

print(f"Nombre total de lignes : {len(df)}")
print(f"Nombre de tableaux français : {len(df_french)}")

df_dutch = df[(df["SCHOOL"] == "Dutch") & (df["FORM"] == "painting")]

print(f"Nombre total de lignes : {len(df)}")
print(f"Nombre de tableaux néerlandais : {len(df_dutch)}")

Nombre total de lignes : 52867
Nombre de tableaux français : 4410
Nombre total de lignes : 52867
Nombre de tableaux néerlandais : 4375

In [4]:
print(df_french.shape)
print(df_dutch.shape)

(4410, 11)
(4375, 11)

In [5]:
def page_url_to_filename(page_url: str) -> str:
    img_url = page_url.replace("/html/", "/detail/").replace(".html", ".jpg")
    return img_url.split("/")[-1]

df_french["fname"] = df_french["URL"].apply(page_url_to_filename)

/tmp/ipykernel_228658/713090511.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_french["fname"] = df_french["URL"].apply(page_url_to_filename)

In [6]:
import os, shutil

src_dir = "../../data/raw/all"
dst_dir = "../../data/processed/french"
os.makedirs(dst_dir, exist_ok=True)

copied = 0
missing = []

for fname in df_french["fname"].unique():
    src = os.path.join(src_dir, fname)
    dst = os.path.join(dst_dir, fname)
    if os.path.exists(src):
        shutil.copy2(src, dst)
        copied += 1
    else:
        missing.append(fname)

print(f"✅ {copied} portraits copiés dans {dst_dir}")
print(f"⚠️ {len(missing)} fichiers manquants (peut-être non téléchargés)")

✅ 3778 portraits copiés dans ../../data/processed/french
⚠️ 0 fichiers manquants (peut-être non téléchargés)

In [7]:
df_dutch["fname"] = df_dutch["URL"].apply(page_url_to_filename)

src_dir = "../../data/raw/all"
dst_dir = "../../data/processed/dutch"
os.makedirs(dst_dir, exist_ok=True)

copied = 0
missing = []

for fname in df_dutch["fname"].unique():
    src = os.path.join(src_dir, fname)
    dst = os.path.join(dst_dir, fname)
    if os.path.exists(src):
        shutil.copy2(src, dst)
        copied += 1
    else:
        missing.append(fname)

print(f"✅ {copied} portraits copiés dans {dst_dir}")
print(f"⚠️ {len(missing)} fichiers manquants (peut-être non téléchargés)")

/tmp/ipykernel_228658/2956955154.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_dutch["fname"] = df_dutch["URL"].apply(page_url_to_filename)

✅ 3221 portraits copiés dans ../../data/processed/dutch
⚠️ 0 fichiers manquants (peut-être non téléchargés)